blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'

#URLパターンを登録するためのリスト
urlpatterns = [
    
    path('', views.IndexView.as_view(), name='index'),
    path(
        'blog-detail/<int:pk>',
        views.BlogDetail.as_view(),
        name='blog_detail'
        ),
    
    path(
        'science-list/',
        views.ScienceView.as_view(),
        name='science_list'
        ),
    path(
        'dailylife-list/',
        views.DailylifeView.as_view(),
        name='dailylife_list'
        
        ),
    path(
        'music-list/',
        views.MusicView.as_view(),
        name='music_list'        
        )
    
    ]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    
]

blogapp/models.py
from django.db import models

# Create your models here.
class BlogPost(models.Model):
    
    CATEGORY =(('science', '科学のこと'),
               ('dailylife', '日常のこと'),
               ('music', '音楽のこと'))
    
    #タイトル用のフィールド（column）
    title = models.CharField(
        verbose_name ='タイトル',
        max_length= 200
        )
    
    #本文中のフィールド
    content = models.TextField(
        verbose_name='本文'
        )
    #投稿日時のフィールド
    posted_at = models.DateTimeField(
        verbose_name = '投稿日時',
        auto_now_add = True #日時を自動追加
        )
    #カテゴリのフィールド
    category = models.CharField(
        verbose_name='カテゴリ',
        max_length = 50,
        choices = CATEGORY
        )
    
    def __str__(self):
        return self.title
    
    
    
    

blogapp/views.py
from django.shortcuts import render

#ListViewをインポート
from django.views.generic import ListView, DetailView

#モデルBlogPostをインポート
from .models import BlogPost

class IndexView(ListView):
    
    '''トップページのビュー
    

    
    
    
    '''
    
    
    #index.htmlをレンダリングする
    template_name = 'index.html'
        
    #object_listキーの別名を設定
    context_object_name = 'orderby_records'
    
    #BlogPostのレコードを投稿日時の降順で並び替える(データベースへの要求を行うためのオブジェクト)
    queryset = BlogPost.objects.order_by('-posted_at')
    

class BlogDetail(DetailView):
    '''
    詳細ページのview
    
    '''
    
    template_name = 'post.html'
    
    model = BlogPost
    
class ScienceView(ListView):
    template_name = 'science_list.html'
    
    model = BlogPost
    
    context_object_name = 'science_records'
    
    queryset = BlogPost.objects.filter(
        category='science').order_by('-posted_at')
    
        
class DailylifeView(ListView):
    template_name = 'dailylife_list.html'
    
    model = BlogPost
    
    context_object_name = 'dailylife_records'
    
    queryset = BlogPost.objects.filter(
        category='dailylife').order_by('-posted_at')
        
class MusicView(ListView):
    template_name = 'music_list.html'
    
    model = BlogPost
    
    context_object_name = 'music_records'
    
    queryset = BlogPost.objects.filter(
        category='music').order_by('-posted_at')
    
    

blogapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %} />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href={% url 'blogapp:index' %}>Django's Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:science_list' %}">SCIENCE</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:dailylife_list' %}">DAILYLIFE</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blogapp:music_list' %}">MUSIC</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        {% block header %}{% endblock %}
        <!-- Main Content-->
        {% block contents %}{% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="https://twitter.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://facebook.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://github.co.jp/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Django's Blog 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static 'js/scripts.js' %}></script>
    </body>
</html>

blogapp/templates/dailylife_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Django's Blog - Dailylife{% endblock %}

    

        {% block header %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Django's Blog - Dailylife</h1>
                            <span class="subheading">Dailylifeカテゴリの記事一覧</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        
        {% endblock %}
        {% block contents %}
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% for record in daily_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        
                            <!--詳細ページへのリンクを設定-->                            
                        <a href="{% url 'blogapp:blog_detail' record.pk %}">

                            <!--記事のタイトル-->                            
                            <h2 class="post-title">
                                 <!--titleフィールドを出力-->
                                 {{record.title}}</h2>
                            <!--投稿記事の本文-->
                            <h3 class="post-subtitle">
                                <span style="font-size : 14pt">
                            <!--contentフィールドを出力, 文字数制限を50にする-->
                                {{record.content|truncatechars:50}}
                                </span>
                            </h3>
                        </a>
                        
                        <!--投稿日時とカテゴリ-->                        
                        <p class="post-meta">
                            <a href="#">Django's Blog</a>
                            
                            <!-- posted_atフィールドを出力-->
                            {{record.posted_at}}に投稿/カテゴリ:
                            
                            <!-- categoryフィールドを出力-->
                            {{record.category}}</p>
                        </p>
                </div>
                    
                    <!-- Divider -->
                    <hr class="my-4" />
                    
                    {% endfor %}
 
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
        </div>
        {% endblock %}

blogapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Django's Blog{% endblock %}

    

        {% block header %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Django's Blog</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        
        {% endblock %}
        {% block contents %}
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% for record in orderby_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        
                            <!--詳細ページへのリンクを設定-->                            
                        <a href="{% url 'blogapp:blog_detail' record.pk %}">

                            <!--記事のタイトル-->                            
                            <h2 class="post-title">
                                 <!--titleフィールドを出力-->
                                 {{record.title}}</h2>
                            <!--投稿記事の本文-->
                            <h3 class="post-subtitle">
                                <span style="font-size : 14pt">
                            <!--contentフィールドを出力, 文字数制限を50にする-->
                                {{record.content|truncatechars:50}}
                                </span>
                            </h3>
                        </a>
                        
                        <!--投稿日時とカテゴリ-->                        
                        <p class="post-meta">
                            <a href="#">Django's Blog</a>
                            
                            <!-- posted_atフィールドを出力-->
                            {{record.posted_at}}に投稿/カテゴリ:
                            
                            <!-- categoryフィールドを出力-->
                            {{record.category}}</p>
                        </p>
                </div>
                    
                    <!-- Divider -->
                    <hr class="my-4" />
                    
                    {% endfor %}
 
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
        </div>
        {% endblock %}

blogapp/templates/music_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Django's Blog - Music{% endblock %}

    

        {% block header %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Django's Blog</h1>
                            <span class="subheading">Musicカテゴリの記事一覧</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        
        {% endblock %}
        {% block contents %}
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% for record in music_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        
                            <!--詳細ページへのリンクを設定-->                            
                        <a href="{% url 'blogapp:blog_detail' record.pk %}">

                            <!--記事のタイトル-->                            
                            <h2 class="post-title">
                                 <!--titleフィールドを出力-->
                                 {{record.title}}</h2>
                            <!--投稿記事の本文-->
                            <h3 class="post-subtitle">
                                <span style="font-size : 14pt">
                            <!--contentフィールドを出力, 文字数制限を50にする-->
                                {{record.content|truncatechars:50}}
                                </span>
                            </h3>
                        </a>
                        
                        <!--投稿日時とカテゴリ-->                        
                        <p class="post-meta">
                            <a href="#">Django's Blog</a>
                            
                            <!-- posted_atフィールドを出力-->
                            {{record.posted_at}}に投稿/カテゴリ:
                            
                            <!-- categoryフィールドを出力-->
                            {{record.category}}</p>
                        </p>
                </div>
                    
                    <!-- Divider -->
                    <hr class="my-4" />
                    
                    {% endfor %}
 
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
        </div>
        {% endblock %}

blogapp/templates/post.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Django's Blog{% endblock %}

        {% block header %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'assets/img/post-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>{{object.title}}</h1>
                            <h2 class="subheading">{{object.content|truncatechars:30}}</h2>
                            <span class="meta">
                                <!--トップページにリンクする-->
                                <a href={% url 'blogapp:index' %}>Django's Blog</a>
                                <!--投稿日時-->
                                {{object.posted_at}}に投稿/カテゴリ：
                                <!--カテゴリフィールドを出力-->
                                {{object.category}}</span>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Post Content-->
        {% block contents %}
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>{{object.content}}</p>
                    </div>
                </div>
            </div>
        </article>
        <!--水平線を追加-->
        <hr>
        {% endblock %}

blogapp/templates/science_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Django's Blog - Science{% endblock %}

    

        {% block header %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Django's Blog</h1>
                            <span class="subheading">Scienceカテゴリの記事一覧</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        
        {% endblock %}
        {% block contents %}
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% for record in science_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        
                            <!--詳細ページへのリンクを設定-->                            
                        <a href="{% url 'blogapp:blog_detail' record.pk %}">

                            <!--記事のタイトル-->                            
                            <h2 class="post-title">
                                 <!--titleフィールドを出力-->
                                 {{record.title}}</h2>
                            <!--投稿記事の本文-->
                            <h3 class="post-subtitle">
                                <span style="font-size : 14pt">
                            <!--contentフィールドを出力, 文字数制限を50にする-->
                                {{record.content|truncatechars:50}}
                                </span>
                            </h3>
                        </a>
                        
                        <!--投稿日時とカテゴリ-->                        
                        <p class="post-meta">
                            <a href="#">Django's Blog</a>
                            
                            <!-- posted_atフィールドを出力-->
                            {{record.posted_at}}に投稿/カテゴリ:
                            
                            <!-- categoryフィールドを出力-->
                            {{record.category}}</p>
                        </p>
                </div>
                    
                    <!-- Divider -->
                    <hr class="my-4" />
                    
                    {% endfor %}
 
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
                </div>
            </div>
        </div>
        {% endblock %}